### ISSUE TITLE
Standardization / OpenAPI 3

### ISSUE THREAD

**Issue by AbdBarho** [leszekhanusz/diffusion-ui#38]
Hi! I like what you are doing here!

Unfortunately, I think the complexity will grow exponentially if you want to support different UIs with different parameters.

Would it make sense to come up with & propose an API specification for sd-backends? this can them be implemented by the different repos and this UI will work out of the box.

**Comment by leszekhanusz** [comment]
That would be awesome but would be really hard to pull off in practice with the number of innovations taking place at different places. You'll need to synchronize all the different forks to add a feature and I don't see it happening.

What would help a lot is if each backend would try to keep their own api somewhat stable:
 - not changing the gradio function_id
 - only adding new inputs at the end of the input list and allow them to be null if the feature is not required

That way is a feature is added, it won't impact the existing frontends.
