### ISSUE TITLE
Error 500 when third party scripts are loaded.

### ISSUE THREAD

**Issue by ActuallyAuggie** [leszekhanusz/diffusion-ui#43]
Diffusion UI works when only included scripts are loaded, but sends a 500 error message when a third party script is also loaded.

#40 #42 probably related, but a different solution will likely be required.

Guessing that [gradio api listing](https://github.com/gradio-app/gradio/issues/2364) is a blocking issue, but wanted to make you aware.

Console error message slightly different:

Traceback (most recent call last):
  File "D:\teststable\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "D:\teststable\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 739, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\teststable\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 638, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "D:\teststable\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1067, in preprocess
    return self.choices.index(x)
ValueError: '' is not in list

**Comment by leszekhanusz** [comment]
Yes, nothing I could do about that until gradio supports introspection...

**Comment by leszekhanusz** [comment]
I've just noticed that all the api info can be found on `http://127.0.0.1:7860/config` :rocket:

**Comment by leszekhanusz** [comment]
Once the bug has been fixed in the automatic1111 fork, I'll merge the PR #46 which should fix this issue here.

**Comment by leszekhanusz** [comment]
@ActuallyAuggie Could you please verify that it now works correctly (Warning: you really need the latest automatic1111 version - as of 30 minutes ago)

**Comment by ActuallyAuggie** [comment]
Fixed for me!  I confirm the UI now works with third party scripts loaded.  Thanks!
