### ISSUE TITLE
How to parse Gradio config?

### ISSUE THREAD

**Issue by Cyberes** [leszekhanusz/diffusion-ui#71]
I'm working on an API for Automatic's webui but I'm struggling to parse the Gradio config file. There's no documentation and from what I understand it's linking parts of the UI together. How do you do it for this project? I tried to port your code to Python but it isn't perfect and I'm not getting the same results. Just would like some advice.

**Comment by leszekhanusz** [comment]
The easier way to check for differences is to use the network tab on Chrome to compare what is actually sent from your code and from the original webui.

What's complicated is to find the `fn_index` for each function which might change between versions of the webui.
I'm using this [complicated method](https://github.com/leszekhanusz/diffusion-ui/blob/4a19c11b6f95b264271cee81bded79a0ef9bfbe1/src/stores/backend.js#L685) to find those index for different methods of the API.

In [my backend info json](https://github.com/leszekhanusz/diffusion-ui/blob/main/src/backends/gradio/stable-diffusion-automatic1111.json), I have `fn_index` sections ([example](https://github.com/leszekhanusz/diffusion-ui/blob/4a19c11b6f95b264271cee81bded79a0ef9bfbe1/src/backends/gradio/stable-diffusion-automatic1111.json#L51)) which defines the condition to get that index. For the `inputs`, `outputs` and `targets` values, you actually have to go check for correspondences in the `components` section of the gradio config. So I could say for example, find me the function where the trigger is `change` and where the first target component has the label `Stable Diffusion checkpoint`

Once you have your `fn_index`, you can find all the inputs for that function in the `dependencies` section of the gradio config. You always have to send all those inputs in the correct order to the backend and for each input you don't specifically change you have to put the default value.

I hope this helps.

**Comment by Cyberes** [comment]
Yeah, I was working on getGradioConfigFunctionIndex. What a beast. Thanks for the info, I'll see what I can do.
