### ISSUE TITLE
Automatic1111 arguments have changed

### ISSUE THREAD

**Issue by benrugg** [leszekhanusz/diffusion-ui#74]
First of all: Love this project. I think it's really valuable that you made it. And I know it's helped a number of others in the community integrate with Automatic1111, standing on your shoulders, so to speak.

It looks like the Automatic1111 web ui has changed quite a bit in the past few weeks. From what I can tell, yesterday there was a breaking change in the arguments, so now img2img needs to be called differently. Compare these two files (in my project, using Automatic1111) for a quick view of the changes: [Oct 20 params](https://github.com/benrugg/AI-Render/blob/main/sd_backends/automatic1111/params-v2022-10-20.json) / [Oct 21 params](https://github.com/benrugg/AI-Render/blob/main/sd_backends/automatic1111/params-v2022-10-21.json)

Note that even `fn_index` changed from 33 to 35. 

I think that more changes happened today, and the arguments actually might look different again. 

Given how brittle this integration is, it's a good thing that an API is looking close:
 - https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3381
 - https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/765

**Comment by leszekhanusz** [comment]
I just tested with the latest automatic1111 version and https://diffusionui.com works correctly for me, without any modification from my side.
Note that my implementation is robust relative to `fn_index` changes, see issue #71 for an explanation on how it works.

**Comment by leszekhanusz** [comment]
And yes, an official API from automatic1111 will definitely be very useful for everybody.

**Comment by benrugg** [comment]
Oh, sweet, I will check that out. Thanks for the quick reply. And when I have more time, I'll try to see what's going wrong on my end.

**Comment by leszekhanusz** [comment]
The problem you had was probably related to issue #75 caused by a recent change in gradio.

**Comment by benrugg** [comment]
Awesome. Not sure which of your fixes did it, but #75, #76 or #77 restored everything to working order me as well. Thank you!
