### ISSUE TITLE
updates needed for horde generation

### ISSUE THREAD

**Issue by Efreak** [leszekhanusz/diffusion-ui#88]
1. The stable horde backend is returning a 403 error with default settings because the sampler defaults to k_dpm_2 at 30 steps; you need to be signed in (ie, not anonymous) to generate >25 steps on heun or dpm2

As the message response says[^1]: 

[^1]: it would be a good idea to include this message, not direct the user to outdated documentation for another service; the documentation should probably also link to the horde policy on this. But that's ok, because the horde policy is _also_ outdated, *and* doesn't have an anchor that would allow you to link directly to that part of the page.

> Due to heavy demand, for requests over 832x832 or over 50 steps (25 for k_heun and k_dpm_2*), and for 12 or more weights, the client needs to already have the required kudos. This request requires 0.0 kudos to fulfil.

The step counts are permanent, afaik, while the image size varies based on horde usage.

2. By default, images are returned as r2 image URLs, not as base64 anymore. You need to either display the returned URL or add `r2:false` to the request. **returned images will *not* display correctly until this is fixed**

**Comment by leszekhanusz** [comment]
Sorry, [I just removed the Stable Horde support](https://github.com/leszekhanusz/diffusion-ui/pull/90).
There was just not enough demand for it and it was not working for a long time already.
Other alternatives which are up-to-date with the latest changes are available on the Stable Horde website.
