### ISSUE TITLE
Is this SillyTraven but for SD ? can it support other Api service like firefly ?

### ISSUE THREAD

**Issue by tukangcode** [leszekhanusz/diffusion-ui#89]
Hi this me, i comment to at webui disscusion page but i will ask here to just in case. So are this work smiliar to SillyTraven ? https://github.com/SillyTavern/SillyTavern where i can use this as frontend and using API key as backend ?

**Comment by leszekhanusz** [comment]
That was the goal at first but as it did not generate enough interest I'm now concentrating on an interface for the Automatic1111 backend.
