### ISSUE TITLE
why I run this with error

### ISSUE THREAD

**Issue by Gt720** [leszekhanusz/diffusion-ui#91]
I already run my stable diffusion backend in my computer. And the project can get config successfully, but nothing happen. 

Until I find this error. Whats happen and how can I fix this error, 

Thank you for taking time out of your busy schedule to answer my questions!

![image](https://github.com/leszekhanusz/diffusion-ui/assets/138437282/934d9482-c089-43fd-89a5-f35902451e42)
![image](https://github.com/leszekhanusz/diffusion-ui/assets/138437282/8a723419-1283-4adc-b7be-14f77e1147cb)

**Comment by leszekhanusz** [comment]
Which backend are you using? Which version?

Please post the json file received at [http://127.0.0.1:7860/config](http://127.0.0.1:7860/config)

**Comment by leszekhanusz** [comment]
I'm closing this as I have not received a response.
